# Generated by Django 4.0.4 on 2022-06-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('hdmemoria', models.CharField(max_length=30)),
                ('memoriaram', models.CharField(max_length=30)),
                ('procesador', models.CharField(max_length=30)),
                ('sistema', models.CharField(max_length=30)),
                ('pantalla', models.CharField(max_length=30)),
                ('precio', models.IntegerField(max_length=30)),
            ],
        ),
    ]
