# Generated by Django 4.0.4 on 2022-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('pantalla', models.CharField(max_length=30)),
                ('precio', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('características', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=30)),
            ],
        ),
    ]
