# Generated by Django 4.0.4 on 2022-06-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0003_pc_notebooks_delete_computadoras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitores',
            name='características',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
