# Generated by Django 4.0.4 on 2022-06-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0006_rename_características_monitores_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perifericos',
            name='caracteristicas',
            field=models.CharField(max_length=90),
        ),
    ]
