# Generated by Django 4.0.4 on 2022-06-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0007_alter_perifericos_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perifericos',
            name='caracteristicas',
            field=models.CharField(max_length=60),
        ),
    ]
