# Generated by Django 4.0.4 on 2022-06-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronica', '0008_alter_perifericos_caracteristicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitores',
            options={'verbose_name': 'monitor', 'verbose_name_plural': 'monitores'},
        ),
        migrations.AlterModelOptions(
            name='pc_notebooks',
            options={'verbose_name': 'pc_notebook', 'verbose_name_plural': 'pc_notebooks'},
        ),
        migrations.AlterModelOptions(
            name='perifericos',
            options={'verbose_name': 'periferico', 'verbose_name_plural': 'perifericos'},
        ),
    ]
